- name: Packer Ansible Test
  hosts: all
  remote_user: ubuntu
  # Commented these out because gather_facts try to remove the non-existent /root/.ansible and it causes a fatal error during its cleanup
  #become: true
  #become_user: root

  environment:
    PERHAPS: "Perhaps"
  tasks:
    - name: Prepare ansible home tmp folder
      ansible.builtin.shell:
        cmd: rm -r ~/.ansible
    - name: Simple Debug
      ansible.builtin.debug:
        msg: "{{ ansible_env.PERHAPS }}"
    - name: Simple Debug 2
      ansible.builtin.debug:
        msg: "{{ lookup('env', 'PERHAPS') }}"
