- name: Packer Ansible Test
  hosts: all
  remote_user: ubuntu
  become: true
  become_user: root

  environment:
    EXAMPLE_KEY: "EXAMPLE_KEY from this Ansible Playbook"
  tasks:
    - name: Simple Debug
      ansible.builtin.debug:
        msg: "{{ ansible_env.EXAMPLE_KEY }}"
    - name: Simple Debug 2
      ansible.builtin.debug:
        msg: "{{ lookup('env', 'EXAMPLE_KEY') }}"
